language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "abbinav-github"
    token:
      secure: "f61460b466d5a822b3c86001785ab6b271668d04"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
